apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
data:
  PORT: "8080"
  REDIS_ADDR: "redis:6379"
  SERVER_READ_TIMEOUT: "5s"
  SERVER_WRITE_TIMEOUT: "10s"
  SERVER_IDLE_TIMEOUT: "60s"
  CACHE_TTL: "10m"
  PROVIDER_TIMEOUT: "6s"
  REQUEST_TIMEOUT: "8s"