apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-api
  namespace: weather-app
  labels:
    release: monitoring  # matches our Prometheus installation name
spec:
  namespaceSelector:
    matchNames:
      - weather-app
  selector:
    matchLabels:
      app: weather-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s